# Generated by Django 5.0.1 on 2024-05-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Info'), ('error', 'Error'), ('success', 'Success')], max_length=20)),
                ('log_string', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('source', models.CharField(max_length=50)),
                ('metadata', models.JSONField()),
            ],
        ),
    ]
